### ISSUE TITLE
No content in /processed/derived, no video posters/thumbnails

### ISSUE THREAD

**Issue by joshnat** [ShaneIsrael/fireshare#147]
**Describe the bug**
App is not creating video posters, not populating /processed/derived directory

**To Reproduce**
1. Open Fireshare
2. See videos in table/tile mode
3. See only empty tiles with video name and play info, but no thumbnail/poster and no duration.
4. Hovering over the tile shows an animated preview of the video
5. Click manual scan button
6. Check /data and /processed folders on Docker host
7. /data shows updates to config.json today, but no update to db.sqlite since yesterday
8. /processed has no items in derived or video_links directories

Log snippet 
```
2022-10-12 21:16:34,911 INFO    cli.scan_videos:84 | No new videos found, checked 4152 files.
2022-10-12 21:16:35,333 INFO    cli.scan_videos:106 | Verifying 4,007 video files still exist...
2022-10-12 21:16:44,868 INFO    __init__.update_config:27 | Validating configuration file...
2022-10-12 21:16:45,046 INFO    cli.sync_metadata:145 | Found 3,474 videos without metadata
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fireshare/util.py", line 47, in get_media_info
    data = json.loads(sp.check_output(cmd.split()).decode('utf-8'))
  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_entries', 'stream', '/processed/video_links/99aa06d3014798d86001c324468d497f.mp4']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/fireshare", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fireshare/cli.py", line 265, in bulk_import
    ctx.invoke(sync_metadata)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fireshare/cli.py", line 149, in sync_metadata
    info = util.get_media_info(vpath)
  File "/usr/local/lib/python3.9/site-packages/fireshare/util.py", line 50, in get_media_info
    logger.warn('Could not extract video info', ex)
Message: 'Could not extract video info'
Arguments: (CalledProcessError(1, ['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_entries', 'stream', '/processed/video_links/99aa06d3014798d86001c324468d497f.mp4']),)
Traceback (most recent call last):
  File "/usr/local/bin/fireshare", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fireshare/cli.py", line 265, in bulk_import
    ctx.invoke(sync_metadata)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fireshare/cli.py", line 150, in sync_metadata
    vcodec = [i for i in info if i['codec_type'] == 'video'][0]
TypeError: 'NoneType' object is not iterable
```

**Expected behavior**
See Fireshare-generated posters/thumbnails and duration for each video

**Screenshots**
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/7060046/195404198-11c01922-9e05-4e7c-8227-d479f2a96c42.png">

**Desktop (please complete the following information):**
 - Client Browser Chrome 106.0.5249.103 for Mac ARM
 - Client PC MacOS 12.6 ARM
 - Server Docker version 20.10.18, build b40c2f6
 - Server Ubuntu 20.04
 - Fireshare v1.2.4

**Additional context**
Running container with PGID=1000 and PUID=1000, and same ownership of /videos

**Comment by ShaneIsrael** [comment]
Do you have any other non video files in your videos folder? Are the videos in that folder only of the supported file types? It looks like the process is failing because of of the files is not a video.

**Comment by joshnat** [comment]
I will check.  There may be images or other files in the folders.  Would that account for the thumbnails not being generated for the compatible videos that are also in the folders?

**Comment by Shane-stage** [comment]
Yes. The process is failing as soon as it gets to a non video file. The folder must not contain other files or the process will fail and thus no thumbnail or metadata generation.

**Comment by joshnat** [comment]
Got it, thanks.  I input a smaller directory with only video files, and the thumbnails are populating.
