### ISSUE TITLE
Thumbnail creation failed when there are many files

### ISSUE THREAD

**Issue by sanwecn** [ShaneIsrael/fireshare#150]
I have about 2000 videos. When I import fewer files, I can successfully create thumbnail images. If there are too many files, an error will occur.
![image](https://user-images.githubusercontent.com/101993515/198850346-4e9464b2-8c0f-4671-803b-3d11955a5c3d.png)

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/fireshare/util.py", line 47, in get_media_info
    data = json.loads(sp.check_output(cmd.split()).decode('utf-8'))
  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_entries', 'stream', '/processed/video_links/f176ee92910376ca6edbf0bdeda24707.mp4']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/fireshare", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fireshare/cli.py", line 265, in bulk_import
    ctx.invoke(sync_metadata)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fireshare/cli.py", line 149, in sync_metadata
    info = util.get_media_info(vpath)
  File "/usr/local/lib/python3.9/site-packages/fireshare/util.py", line 50, in get_media_info
    logger.warn('Could not extract video info', ex)
Message: 'Could not extract video info'
Arguments: (CalledProcessError(1, ['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_entries', 'stream', '/processed/video_links/f176ee92910376ca6edbf0bdeda24707.mp4']),)
Traceback (most recent call last):
  File "/usr/local/bin/fireshare", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fireshare/cli.py", line 265, in bulk_import
    ctx.invoke(sync_metadata)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fireshare/cli.py", line 150, in sync_metadata
    vcodec = [i for i in info if i['codec_type'] == 'video'][0]
TypeError: 'NoneType' object is not iterable

**Comment by ShaneIsrael** [comment]
The issue isn't that you have too many files, you have either a corrupt video file OR more likely a file in that folder that **is not** a video file. The folder must only contain video files, ideally of the supported video file types. .mp4, .mov, .webm

The file in question is whatever file this symlink is linking too. `/processed/video_links/f176ee92910376ca6edbf0bdeda24707.mp4`, It's likely not an .mp4 file that it is linking to or it is a .mp4 file and its corrupt.

**Comment by ShaneIsrael** [comment]
Closed due to no response, assuming the issue was resolved.
