### ISSUE TITLE
removing file while scan gives an error

### ISSUE THREAD

**Issue by ankapone** [ShaneIsrael/fireshare#262]
v1.2.20, docker

When video  scan going on, some files are deleted, and this give an error:

```
02_surveillance-fireshare-1  | 2024-09-14 11:31:38,048 INFO    cli.scan_videos:79 | Adding new Video 283d67fa4993545a4b6b3b59d73c8ec2 at dir/2024-09-10/2024-09-10_21-18.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-10T18:19:25.080230)
02_surveillance-fireshare-1  | 2024-09-14 11:31:38,221 INFO    cli.scan_videos:79 | Adding new Video 4919a78fa4d55d09b78b7bb3db70bcdd at dir/2024-09-10/2024-09-10_15-49.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-10T12:51:19.046219)
02_surveillance-fireshare-1  | 2024-09-14 11:31:38,356 INFO    cli.scan_videos:79 | Adding new Video 481539e8777d3b962f3d538b1489fb31 at dir/2024-09-10/2024-09-10_07-49.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-10T04:51:06.099017)
02_surveillance-fireshare-1  | 2024-09-14 11:31:38,501 INFO    cli.scan_videos:79 | Adding new Video 97eefb2133059753da5e331cfef621da at dir/2024-09-10/2024-09-10_15-24.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-10T12:25:48.113005)
02_surveillance-fireshare-1  | 2024-09-14 11:31:38,613 INFO    cli.scan_videos:79 | Adding new Video 1f38b8254711af1d28f7d56c2691252e at dir/2024-09-14/2024-09-14_10-13.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T07:14:41.111687)
02_surveillance-fireshare-1  | 2024-09-14 11:31:38,734 INFO    cli.scan_videos:79 | Adding new Video ef48df4091e2310571602740631d70a1 at dir/2024-09-14/2024-09-14_08-06.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T05:07:02.110997)
02_surveillance-fireshare-1  | 2024-09-14 11:31:39,367 INFO    cli.scan_videos:79 | Adding new Video 32d42ed259f6902856d62d8ffc657fa4 at dir/2024-09-14/2024-09-14_08-03.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T05:03:54.103804)
02_surveillance-fireshare-1  | 2024-09-14 11:31:40,345 INFO    cli.scan_videos:79 | Adding new Video 3a6ccf22768c0e2b6385e4f450f817a0 at dir/2024-09-14/2024-09-14_12-01.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T09:02:54.087945)
02_surveillance-fireshare-1  | 2024-09-14 11:31:40,916 INFO    cli.scan_videos:79 | Adding new Video f9aaa482b843419c7cf85727d83a3e86 at dir/2024-09-14/2024-09-14_11-40.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T08:41:28.169396)
02_surveillance-fireshare-1  | 2024-09-14 11:31:41,500 INFO    cli.scan_videos:79 | Adding new Video 8ef5962f380147e6ebfafe692b1a3451 at dir/2024-09-14/2024-09-14_07-53.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T04:53:59.187116)
02_surveillance-fireshare-1  | 2024-09-14 11:31:42,181 INFO    cli.scan_videos:79 | Adding new Video a53b31413232c358462e137a9173cb31 at dir/2024-09-14/2024-09-14_12-00.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T09:01:09.076569)
02_surveillance-fireshare-1  | 2024-09-14 11:31:42,630 INFO    cli.scan_videos:79 | Adding new Video 56b4421a9ede5271980f5e3580395012 at dir/2024-09-14/2024-09-14_07-49.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T04:50:34.120783)
02_surveillance-fireshare-1  | 2024-09-14 11:31:42,891 INFO    cli.scan_videos:79 | Adding new Video 9e1091aabebba157119b5a2b2c364097 at dir/2024-09-14/2024-09-14_09-28.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T06:29:49.124025)
02_surveillance-fireshare-1  | 2024-09-14 11:31:43,187 INFO    cli.scan_videos:79 | Adding new Video 260c014ea8f002e6f99031aea6b78bef at dir/2024-09-14/2024-09-14_11-47.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T08:47:51.083441)
02_surveillance-fireshare-1  | 2024-09-14 11:31:43,392 INFO    cli.scan_videos:79 | Adding new Video 8e53bf3f24a4f55ce1dfbd78771e680b at dir/2024-09-14/2024-09-14_09-15.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T06:17:48.127029)
02_surveillance-fireshare-1  | 2024-09-14 11:31:43,629 INFO    cli.scan_videos:79 | Adding new Video f96ab52594d3086bb6d8069ca272b3c4 at dir/2024-09-14/2024-09-14_09-43.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T06:44:48.062053)
02_surveillance-fireshare-1  | 2024-09-14 11:31:43,808 INFO    cli.scan_videos:79 | Adding new Video 4a9cd58e9501e4fbe62c4248dd4d6559 at dir/2024-09-14/2024-09-14_08-40.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-14T05:41:32.090021)
02_surveillance-fireshare-1  | 2024-09-14 11:31:43,882 INFO    cli.scan_videos:79 | Adding new Video 433b7c8be4d86cae382e642ddad272f6 at dir/2024-09-07/2024-09-07_21-22.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-07T18:22:50.126746)
02_surveillance-fireshare-1  | 2024-09-14 11:31:43,902 INFO    cli.scan_videos:79 | Adding new Video 7e8aac610f3fa1b1cd0456f9d82c74b0 at dir/2024-09-07/2024-09-07_22-59.mp4 (created 2024-09-14T11:25:50.262444, updated 2024-09-07T19:59:47.115014)
02_surveillance-fireshare-1  | Traceback (most recent call last):
02_surveillance-fireshare-1  |   File "/usr/local/bin/fireshare", line 8, in <module>
02_surveillance-fireshare-1  |     sys.exit(cli())
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
02_surveillance-fireshare-1  |     return self.main(*args, **kwargs)
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
02_surveillance-fireshare-1  |     rv = self.invoke(ctx)
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
02_surveillance-fireshare-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
02_surveillance-fireshare-1  |     return ctx.invoke(self.callback, **ctx.params)
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
02_surveillance-fireshare-1  |     return __callback(*args, **kwargs)
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
02_surveillance-fireshare-1  |     return f(get_current_context(), *args, **kwargs)
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/site-packages/fireshare/cli.py", line 375, in bulk_import
02_surveillance-fireshare-1  |     ctx.invoke(scan_videos, root=root)
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
02_surveillance-fireshare-1  |     return __callback(*args, **kwargs)
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/site-packages/fireshare/cli.py", line 58, in scan_videos
02_surveillance-fireshare-1  |     video_id = util.video_id(vf)
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/site-packages/fireshare/util.py", line 39, in video_id
02_surveillance-fireshare-1  |     with path.open('rb', 0) as f:
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/pathlib.py", line 1252, in open
02_surveillance-fireshare-1  |     return io.open(self, mode, buffering, encoding, errors, newline,
02_surveillance-fireshare-1  |   File "/usr/local/lib/python3.9/pathlib.py", line 1120, in _opener
02_surveillance-fireshare-1  |     return self._accessor.open(self, flags, mode)
02_surveillance-fireshare-1  | FileNotFoundError: [Errno 2] No such file or directory: '/videos/dir/2024-09-07/2024-09-07_14-19.mp4'
f
```

**Comment by ankapone** [comment]
Also, would be great to automatically remove orphaned links from sqlite on rescan when files are deleted.

**Comment by ShaneIsrael** [comment]
Will keep this open so that I can look into it.

> Also, would be great to automatically remove orphaned links from sqlite on rescan when files are deleted.

Since fireshare expects its database to be a source of truth this can't be done. If this was done, in the event your videos do not show up or the volume gets unmounted, fireshare would think of everything as an orphaned link and wipe the database. I also keep fireshare as the source of truth so that if you accidentally remove a video or move one to somewhere else, you can move it right back without issue. 

The proper protocol, is that if you need to delete a video, delete the video through the fireshare interface. If you need to move a video, move it normally like you would but you'll need to go into Fireshare and "delete" the video to remove the now invalid entry from it's database.
